#!/bin/bash
#
# gith-monitor       init file for starting up the gith-monitor daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the gith-monitor daemon.
 
PATH=$PATH:/usr/local/bin
NAME="gith-monitor"
PID="/var/run/$NAME.pid"
LOG_DIR="/var/log/$NAME"
SERVER="/usr/local/lib/node_modules/$NAME/index.coffee"
 
if [ ! -d "/var/log/$NAME" ]
then 
  mkdir /var/log/$NAME
fi
 
start() {
  if [ -e $PID ]
  then
    echo "Always running"
    exit
  fi
  forever start -c coffee -l $LOG_DIR/daemon.log -o $LOG_DIR/out.log -e $LOG_DIR/err.log --pidFile $PID $SERVER
}
 
stop() {
  forever stop $SERVER
  rm $PID
}
 
case "$1" in
  start) start;;
  stop) stop;;
  status) forever list | grep $SERVER;;
  restart)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 2
esac

exit $?