#!/usr/bin/env bash

echo -e "\nInstalling gith-monitor as daemon. Hit '^C' to cancel this step.\n"

while true; do
  read -p "Where is your configuration directory? [/etc]: " ETC

  if [ "$ETC" = "" ]; 
  then
    ETC=/etc
  fi

  if [ -d "$ETC" ]; then
    break
  else
    echo -e "> $ETC is not a valid directory\n"
  fi
done

while true; do
  read -p "Where is your startup-scripts directory? [$ETC/init.d]: " INITD

  if [ "$INITD" = "" ]; 
  then
    INITD=$ETC/init.d
  fi

  if [ -d "$INITD" ]; then
    break
  else
    echo -e "> $INITD is not a valid directory\n"
  fi
done

sudo chmod +x scripts/gith-monitor
sudo cp scripts/gith-monitor $INITD/gith-monitor

if [ -f $ETC/gith-monitor ]
then
  while true; do
    read -p "Configuration file already exists: $ETC/gith-monitor. Do you want to replace it? " yn
    case $yn in
        [Yy]* ) sudo cp config.coffee $ETC/gith-monitor; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
  done
else
  sudo cp config.coffee $ETC/gith-monitor
fi

$INITD/gith-monitor start

echo -e "\n\n Gith Monitor is now fully installed and running.\n\nYou can edit the configuration with 'vi $ETC/gith-monitor' and once done, restart the server with '$INITD/gith-monitor restart'."

echo -e "\nNote that you can also have a user based configuration, you can copy $ETC/gith-monitor to ~/.gith-monitor or to ~/.gith-monitor/index.coffee for more complex configurations.\n\n\n"