#!/usr/bin/env bash

echo -e "\nUninstalling gith-monitor as daemon. Hit '^C' to cancel this step.\n"

while true; do
  read -p "Where is your configuration directory? [/etc]: " ETC

  if [ "$ETC" = "" ]; 
  then
    ETC=/etc
  fi

  if [ -d "$ETC" ]; then
    break
  else
    echo -e "> $ETC is not a valid directory\n"
  fi
done

while true; do
  read -p "Where is your startup-scripts directory? [$ETC/init.d]: " INITD

  if [ "$INITD" = "" ]; 
  then
    INITD=$ETC/init.d
  fi

  if [ -d "$INITD" ]; then
    break
  else
    echo -e "> $INITD is not a valid directory\n"
  fi
done

sudo rm $INITD/gith-monitor
sudo rm $ETC/gith-monitor

echo -e "\nDone."